In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('/content/titanic.csv')

In [3]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [4]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [6]:
# name and those column's which  do not have any impact on the output we will drop it out.
data.drop(['Name','Sex','Age','SibSp','Parch','Ticket','Cabin','Embarked'],axis=1,inplace=True)

In [7]:
data.head()

   PassengerId  Survived  Pclass     Fare
0          892         0       3   7.8292
1          893         1       3   7.0000
2          894         0       2   9.6875
3          895         0       3   8.6625
4          896         1       3  12.2875

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Fare         417 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 13.2 KB

In [30]:
data.dropna()

     PassengerId  Survived  Pclass      Fare
0            892         0       3    7.8292
1            893         1       3    7.0000
2            894         0       2    9.6875
3            895         0       3    8.6625
4            896         1       3   12.2875
..           ...       ...     ...       ...
413         1305         0       3    8.0500
414         1306         1       1  108.9000
415         1307         0       3    7.2500
416         1308         0       3    8.0500
417         1309         0       3   22.3583

[417 rows x 4 columns]

In [32]:
data['Fare'] = data['Fare'].fillna(data['Fare'].mean())

In [33]:
data.columns[data.isna().any()]  # to check wheather there is any null value in any of the columns if yes then it will give the column

Index([], dtype='object')

In [34]:
input = data[['Fare','Pclass','PassengerId']]
output = data['Survived']

In [35]:
input

         Fare  Pclass  PassengerId
0      7.8292       3          892
1      7.0000       3          893
2      9.6875       2          894
3      8.6625       3          895
4     12.2875       3          896
..        ...     ...          ...
413    8.0500       3         1305
414  108.9000       1         1306
415    7.2500       3         1307
416    8.0500       3         1308
417   22.3583       3         1309

[418 rows x 3 columns]

In [36]:
output

0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 418, dtype: int64

In [13]:
# now divide the data into test data and train data

In [41]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(input,output,test_size=0.2,random_state=24)

In [42]:
from sklearn.naive_bayes import GaussianNB

In [43]:
gnb = GaussianNB()
model = gnb.fit(x_train,y_train)

In [44]:
model.score(x_test,y_test)

0.6190476190476191

In [48]:
predict = model.predict(x_test)

In [49]:
predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])